# Domain name and port for Musubi Message Server.
domainName: localhost
portNumber: 8080

# Server certificate chain and private key of domain name.
certChain: /path/to/your/cert/chain
certKey: /path/to/your/cert/key

# Relative path for handling HTTP POST requests.
messageRelativePath: /nc

# Relative path for providing websocket service.
websocketRelativePath: /wc

# Path to SQLite database file.
databasePath: /path/to/your/database/file


# Pushbullet Token.
pushbullet:
  token: your.pushbullet.token
